#!/bin/bash
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
export LD_LIBRARY_PATH="$THIS_DIR"
"$THIS_DIR"/wsscat/wsscat "$WSS_URI" | \
  "$THIS_DIR"/receiver/receiver >(python "$THIS_DIR"/../../data_logger.py hare_binance 10000000 600)
